server:
  port: 8003
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: bff
          uri: http://localhost:8004
          predicates:
            - Path=/home/**
        - id: message-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/message/**

        - id: customer-user-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/customer-user/**

