server:
  port: 8000
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现定位器
      routes:
        - id: bff-service
          uri: http://bff-service
          predicates:
            - Path=/member/**
            - Path=/goods/**
        - id: cart-service
          uri: http://cart-service
          predicates:
            - Path=/api/cart/**
        - id: customer-user-service
          uri: http://customer-user-service
          predicates:
            - Path=/api/customer-user/**
        - id: message-service
          uri: http://message-service
          predicates:
            - Path=/api/message/**
        - id: order-service
          uri: http://order-service
          predicates:
            - Path=/api/order/**
        - id: pay-service
          uri: http://pay-service
          predicates:
            - Path=/api/pay/**
        - id: product-service
          uri: http://product-service
          predicates:
            - Path=/api/product/**
    loadbalancer: # 开启负载均衡
      eager-load:
        clients: bff-service,cart-service,customer-user-service,message-service,order-service,pay-service,product-service
